spring:
  datasource:
      url: jdbc:mysql://localhost:3306/bank
      username: root
      password: 12341234
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
     name: Bank
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    static-path-pattern: /resources/**